# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundHausII', '0006_auto_20180225_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, upload_to='project_image'),
        ),
    ]
